const products  = [
    {
        _id: '1',
        name: "apple",
        image: "./../assets/photos/basketlogo.png",
        description: 'fruits',
        brand: 'fruits',
        category: 'food',
        price: 88.5,
        countInStock: 0,
        measure: 100,
        unit:"ml",
        numReviews: 2,
    },
    {
        _id: '2',
        name: "apple",
        image: "./assets/photos/basketlogo.png",
        description: 'fruits',
        brand: 'fruits',
        category: 'food',
        price: 88.5,
        countInStock: 2,
        rating: 4.5,
        measure: 100,
        unit:"ml",
        numReviews: 2,
    },
    {
        _id: '3',
        name: "apple",
        image: "./assets/photos/basketlogo.png",
        description: 'fruits',
        brand: 'fruits',
        category: 'food',
        price: 88.5,
        countInStock: 2,
        rating: 4.5,
        measure: 100,
        unit:"ml",
        numReviews: 2,
    },
    {
        _id: '4',
        name: "apple",
        image: "./assets/photos/basketlogo.png",
        description: 'fruits',
        brand: 'fruits',
        category: 'food',
        price: 88.5,
        countInStock: 2,
        rating: 4.5,
        measure: 100,
        unit:"ml",
        numReviews: 2,
    },


    {
        _id: '5',
        name: "apple lsjdfklsldfj skfds lkdfjlsk dkfljskldf lsjldkfjlsja fd",
        image: "./assets/photos/basketlogo.png",
        description: 'fruits',
        brand: 'fruits',
        category: 'food',
        price: 88.5,
        countInStock: 2,
        rating: 4.5,
        measure: 100,
        unit:"ml",
        numReviews: 2,
    },

    {
        _id: '6',
        name: "apple",
        image: "../assets/photos/basketlogo.png",
        description: 'fruits',
        brand: 'fruits',
        category: 'food',
        price: 88.5,
        countInStock: 2,
        rating: 4.5,
        measure: 100,
        unit:"ml",
        numReviews: 2,
    },
]

export default products